/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ru_chsergeyg_jni_example_n_Calc */

#ifndef _Included_ru_chsergeyg_jni_example_n_Calc
#define _Included_ru_chsergeyg_jni_example_n_Calc
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ru_chsergeyg_jni_example_n_Calc
 * Method:    plus
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_ru_chsergeyg_jni_example_n_Calc_plus
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     ru_chsergeyg_jni_example_n_Calc
 * Method:    minus
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_ru_chsergeyg_jni_example_n_Calc_minus
  (JNIEnv *, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
